### ISSUE TITLE
PA Client refuses connection

### ISSUE THREAD

**Issue by Zlimca** [VoidPollo/BDOAffinity#2]
Since the patch on the 4th January 2023 the client can't establish a connection to the service. 

![image](https://user-images.githubusercontent.com/54706550/211187820-225599a9-ea20-47c6-9b80-9bfb01dcb16b.png)

I'm guessing this is happening because of EAC, but I'm not sure.

When I disable the Affinity with the Disable BDOAffinity.reg and launch the game again it works as usual.

**Comment by OS-Void** [comment]
Still working for me on the steam version, I don't have the non-steam version.
